project:
  type: website
  output-dir: docs

website:
  title: "BIO 5100"
  navbar:
    background: primary
    left:
      - text: "Resources"
        file: index.qmd
#      - about.qmd
    right:
      - icon: house-fill
        href: https://claisselab.com
      - icon: twitter
        href: https://twitter.com/JeremyClaisse
  page-footer:
    left: This is a quarto built website <https://quarto.org/docs/websites>.
    right:  
      - icon: house-fill
        href: https://claisselab.com
      - icon: twitter
        href: https://twitter.com/JeremyClaisse

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

