---
title: "Online Books"
---

#### [Statistical Inference via Data Science (A ModernDive into R and the Tidyverse)](https://moderndive.com/index.html)

-   Introduction to R, RStudio and the Tidyverse for visualizing, wrangling and analyzing your data.

#### [Statistics for the Experimental Bench Biologist by Jeffrey A. Walker](https://middleprofessor.github.io/benchbiostats/chapters/intro.html)

-   (Primary text we follow for BIO 5100/L) Takes a statistical modeling approach, focusing on estimates of effects and uncertainty instead of traditional hypothesis testing. Great option for lab or field based researching working with experimental data. This book is written in a very approachable style, and is a great introduction to the concepts of statistical modeling.

#### [R Graph Gallery](https://r-graph-gallery.com/)
-   A collection of hundreds of plots made with R, with the code to reproduce them. A great resource for finding inspiration and learning how to create specific types of plots.
- also can follow this [tutorial](https://www.data-to-viz.com/) if you aren't sure what type of plot works best for your data.

#### [ggplot2: Elegant Graphics for Data Analysis (3e)](https://ggplot2-book.org/)

-   While this book gives some details on the basics of ggplot2, its primary focus is explaining the Grammar of Graphics that ggplot2 uses, and describing the full details. It is not a cookbook, and won’t necessarily help you create any specific graphic that you need. But it will help you understand the details of the underlying theory, giving you the power to tailor any plot specifically to your needs.


#### [R for Data Science (2nd Edition) by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund](https://r4ds.hadley.nz/)

-   Mostly covers details of using the tidyverse to import, wrangle and get your data ready to analyze.


#### [Fundamentals of Data Visualization (using R) by Claus O. Wilke](https://clauswilke.com/dataviz/index.html)

-   A guide to making visualizations that accurately reflect the data, tell a story, and look professional.

-   The R code for the book can be found on GitHub, at <https://github.com/clauswilke/dataviz>

#### [Spatial Statistics for Data Science: Theory and Practice with R by Paula Moraga](https://www.paulamoraga.com/book-spatial/index.html)

-   Describes statistical methods, modeling approaches, and visualization techniques to analyze spatial data using R. Includes an overview of types of spatial data, relevant R packages for analyzing and visualizing spatial data, explanations of spatial statistics, and fully reproducible examples analyzing areal, geostatistical, and point pattern data.


#### [tidyomics: Open project to create tidy analysis packages for omics data](https://github.com/tidyomics)

-   Tidyomics enables the use of familiar tidyverse verbs (e.g., select, filter, mutate) to manipulate rich data objects in the Bioconductor ecosystem. Importantly, the data objects are not modified, but tidyomics provides a tidy interface to work on the native objects, leveraging existing Bioconductor classes and algorithms.


#### [Guide to Effect Sizes and Confidence Intervals](https://matthewbjane.quarto.pub/guide-to-effect-sizes-and-confidence-intervals)

-   Collaborative guide aims to provide academics, students and researchers with hands-on, step-by-step instructions for calculating effect sizes and confidence intervals for common statistical procedures.

#### [Applied Multivariate Statistics in R](https://uw.pressbooks.pub/appliedmultivariatestatistics/front-matter/introduction/)
-   A guide to using R for multivariate statistics, including PCA, nMDS, RDS, etc. -   It began as notes for students in a course at UW.  These notes provide a background in multivariate analysis of a wide range of data.  Emphasis is on the practical application of these techniques.

#### [Analysis of community ecology data in R by David Zelený](https://www.davidzeleny.net/anadat-r/doku.php/en:start)

-   Multivariate analysis including ordination (e.g., PCA, nMDS plots), cluster analysis and diversity analysis

#### [Applied Biostats by Yaniv Brandvain](https://bookdown.org/ybrandvain/Applied-Biostats/)

-   A "book" written to accompany his biostats course, lots of good guidance and resources.

#### [Tidy Modeling with R by Max Kuhn and Julia Silge](https://www.tmwr.org/)

-   A guide to using the tidymodels framework for modeling and machine learning in R.

#### [Statistical Thinking for the 21st Century by Russell A. Poldrack](https://statsthinking21.github.io/statsthinking21-core-site/index.html#)

-   Modern approach to introductory statistics, good sections on plotting and summarizing data.

#### [Introduction to Modern Statistics by Mine Çetinkaya-Rundel & Johanna Hardin](https://openintro-ims.netlify.app/index.html)

-   Modern take on introductory statistics in an R based format.

#### [Modern Statistics for Modern Biology by Susan Holmes, Wolfgang Huber](https://www.huber.embl.de/msmb/introduction.html)

-   Covers many modern approaches to data analysis, and many different types of data including RNA-Seq, flow-cytometry, taxa abundances, imaging data and single cell measurements.

-   Note some of the R code relies on Base R instead of Tidyverse functions.

#### [Beyond Multiple Linear Regression: Generalized Linear Models and Multilevel Models By Julie Legler and Paul Roback](https://bookdown.org/roback/bookdown-BeyondMLR/)

-   More advanced stats topics including Generalized Linear Models likelihood theory, zero-inflated Poisson, and parametric bootstrapping

#### [Biological Statistics by John H. McDonald](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Biological_Statistics_(McDonald))

-   Traditional statistics text, covering details of specific hypothesis tests (*not R based, but potentially useful if your adviser makes you to use old school statistics*)

#### [The Big Book of R (links to online textbooks)](https://www.bigbookofr.com/)

-   A maintained list of of online R textbook resources
