<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Jeremy Claisse">
<meta name="dcterms.date" content="2024-04-19">
<title>BIO 5100 - BIO 5100 Comparing Means from independent and paired samples</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link rel="stylesheet" href="styles.css">
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">BIO 5100</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Online_Books.html" rel="" target="">
 <span class="menu-text">Online Books</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://claisselab.github.io/BIO_5800L/" rel="" target="">
 <span class="menu-text">BIO 5800L</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://claisselab.github.io/BIO_5100/Example_Code.html" rel="" target="">
 <span class="menu-text">Example Code</span></a>
  </li>  
</ul>
<ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item compact">
    <a class="nav-link" href="https://claisselab.com" rel="" target=""><i class="bi bi-house-fill" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ClaisseLab" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
<div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#load-packages" id="toc-load-packages" class="nav-link active" data-scroll-target="#load-packages">Load Packages</a></li>
  <li><a href="#general-modeling-strategy" id="toc-general-modeling-strategy" class="nav-link" data-scroll-target="#general-modeling-strategy">General modeling strategy:</a></li>
  <li>
<a href="#comparing-means-of-2-independent-samples" id="toc-comparing-means-of-2-independent-samples" class="nav-link" data-scroll-target="#comparing-means-of-2-independent-samples">Comparing means of 2 independent samples</a>
  <ul class="collapse">
<li><a href="#linear-model-w-a-categorical-x-explanatory-variable" id="toc-linear-model-w-a-categorical-x-explanatory-variable" class="nav-link" data-scroll-target="#linear-model-w-a-categorical-x-explanatory-variable">Linear model w/ a categorical X (explanatory) variable</a></li>
  <li><a href="#initial-exploratory-analysis" id="toc-initial-exploratory-analysis" class="nav-link" data-scroll-target="#initial-exploratory-analysis">Initial Exploratory Analysis</a></li>
  <li>
<a href="#checking-assumptions" id="toc-checking-assumptions" class="nav-link" data-scroll-target="#checking-assumptions">Checking assumptions</a>
  <ul class="collapse">
<li><a href="#in-practical-terms-just-check-to-make-sure-during-exploratory-analysis" id="toc-in-practical-terms-just-check-to-make-sure-during-exploratory-analysis" class="nav-link" data-scroll-target="#in-practical-terms-just-check-to-make-sure-during-exploratory-analysis">In practical terms just check to make sure during exploratory analysis:</a></li>
  </ul>
</li>
  <li><a href="#descriptive-statistics-for-comparing-two-groups" id="toc-descriptive-statistics-for-comparing-two-groups" class="nav-link" data-scroll-target="#descriptive-statistics-for-comparing-two-groups">Descriptive Statistics for comparing two groups</a></li>
  <li><a href="#magnitude-of-the-effect-size" id="toc-magnitude-of-the-effect-size" class="nav-link" data-scroll-target="#magnitude-of-the-effect-size">Magnitude of the effect size</a></li>
  <li>
<a href="#fit-linear-model" id="toc-fit-linear-model" class="nav-link" data-scroll-target="#fit-linear-model">Fit linear model</a>
  <ul class="collapse">
<li><a href="#coefficient-table" id="toc-coefficient-table" class="nav-link" data-scroll-target="#coefficient-table">Coefficient table</a></li>
  </ul>
</li>
  <li><a href="#create-emmeans-table" id="toc-create-emmeans-table" class="nav-link" data-scroll-target="#create-emmeans-table">Create emmeans table</a></li>
  <li><a href="#points-means-plot-w-model-95-cis" id="toc-points-means-plot-w-model-95-cis" class="nav-link" data-scroll-target="#points-means-plot-w-model-95-cis">Points &amp; means plot w/ (model) 95% CIs</a></li>
  <li><a href="#contrasts-table-corresponding-effects-plot" id="toc-contrasts-table-corresponding-effects-plot" class="nav-link" data-scroll-target="#contrasts-table-corresponding-effects-plot">Contrasts table &amp; corresponding “effects” plot</a></li>
  <li><a href="#effects-plot-w-95-ci" id="toc-effects-plot-w-95-ci" class="nav-link" data-scroll-target="#effects-plot-w-95-ci">Effects plot w/ 95% CI</a></li>
  <li><a href="#combine-plots-into-a-single-results-figure" id="toc-combine-plots-into-a-single-results-figure" class="nav-link" data-scroll-target="#combine-plots-into-a-single-results-figure">Combine plots into a single results figure</a></li>
  <li><a href="#export-save-plot-to-a-.png-file-with-ggsave" id="toc-export-save-plot-to-a-.png-file-with-ggsave" class="nav-link" data-scroll-target="#export-save-plot-to-a-.png-file-with-ggsave">Export (save) plot to a .png file with ggsave()</a></li>
  <li><a href="#results-sentence" id="toc-results-sentence" class="nav-link" data-scroll-target="#results-sentence">Results sentence:</a></li>
  <li>
<a href="#two-sample-t-test-hypothesis-test" id="toc-two-sample-t-test-hypothesis-test" class="nav-link" data-scroll-target="#two-sample-t-test-hypothesis-test">Two-sample t-test (hypothesis test)</a>
  <ul class="collapse">
<li><a href="#welchs-t-test-is-default-that-the-t.test-function-in-r-runs" id="toc-welchs-t-test-is-default-that-the-t.test-function-in-r-runs" class="nav-link" data-scroll-target="#welchs-t-test-is-default-that-the-t.test-function-in-r-runs">Welch’s t-test is default that the <code>t.test()</code> function in R runs</a></li>
  <li><a href="#extra-use-of-broom-package-tidy-function-w-t.test" id="toc-extra-use-of-broom-package-tidy-function-w-t.test" class="nav-link" data-scroll-target="#extra-use-of-broom-package-tidy-function-w-t.test">Extra: Use of broom package tidy() function w/ t.test()</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#paired-sample-matched-pair-experiment-mean-comparison" id="toc-paired-sample-matched-pair-experiment-mean-comparison" class="nav-link" data-scroll-target="#paired-sample-matched-pair-experiment-mean-comparison">Paired-sample (matched pair) experiment mean comparison</a>
  <ul class="collapse">
<li><a href="#use-factor-function-to-covert-numeric-or-character-to-a-factor" id="toc-use-factor-function-to-covert-numeric-or-character-to-a-factor" class="nav-link" data-scroll-target="#use-factor-function-to-covert-numeric-or-character-to-a-factor">Use <code>factor()</code> function to covert numeric or character to a factor</a></li>
  <li><a href="#initial-exploratory-analysis-for-paired-data" id="toc-initial-exploratory-analysis-for-paired-data" class="nav-link" data-scroll-target="#initial-exploratory-analysis-for-paired-data">Initial Exploratory Analysis (for Paired Data)</a></li>
  <li><a href="#convert-paired-data-to-differences-between-pairs" id="toc-convert-paired-data-to-differences-between-pairs" class="nav-link" data-scroll-target="#convert-paired-data-to-differences-between-pairs">Convert Paired Data to Differences (between pairs)</a></li>
  <li><a href="#exploratory-analysis-with-the-difference-values" id="toc-exploratory-analysis-with-the-difference-values" class="nav-link" data-scroll-target="#exploratory-analysis-with-the-difference-values">Exploratory analysis with the difference values</a></li>
  <li><a href="#checking-assumptions-1" id="toc-checking-assumptions-1" class="nav-link" data-scroll-target="#checking-assumptions-1">Checking assumptions</a></li>
  <li><a href="#descriptive-statistics-of-the-difference-values" id="toc-descriptive-statistics-of-the-difference-values" class="nav-link" data-scroll-target="#descriptive-statistics-of-the-difference-values">Descriptive statistics of the difference values</a></li>
  <li>
<a href="#fit-linear-model-1" id="toc-fit-linear-model-1" class="nav-link" data-scroll-target="#fit-linear-model-1">Fit linear model</a>
  <ul class="collapse">
<li><a href="#coefficient-table-1" id="toc-coefficient-table-1" class="nav-link" data-scroll-target="#coefficient-table-1">Coefficient table</a></li>
  </ul>
</li>
  <li><a href="#create-emmeans-table-1" id="toc-create-emmeans-table-1" class="nav-link" data-scroll-target="#create-emmeans-table-1">Create emmeans table</a></li>
  <li><a href="#points-mean-plot-w-model-95-cis" id="toc-points-mean-plot-w-model-95-cis" class="nav-link" data-scroll-target="#points-mean-plot-w-model-95-cis">Points &amp; Mean plot w/ (model) 95% CIs</a></li>
  <li><a href="#combine-plots-into-a-single-results-figure-1" id="toc-combine-plots-into-a-single-results-figure-1" class="nav-link" data-scroll-target="#combine-plots-into-a-single-results-figure-1">Combine plots into a single results figure</a></li>
  <li><a href="#export-save-plot-to-a-.png-file-with-ggsave-1" id="toc-export-save-plot-to-a-.png-file-with-ggsave-1" class="nav-link" data-scroll-target="#export-save-plot-to-a-.png-file-with-ggsave-1">Export (save) plot to a .png file with ggsave()</a></li>
  <li><a href="#results-sentence-1" id="toc-results-sentence-1" class="nav-link" data-scroll-target="#results-sentence-1">Results sentence</a></li>
  <li>
<a href="#paired-sample-t-test-or-one-sample-t-test-w-mu-0" id="toc-paired-sample-t-test-or-one-sample-t-test-w-mu-0" class="nav-link" data-scroll-target="#paired-sample-t-test-or-one-sample-t-test-w-mu-0">Paired-Sample t-test (or one-sample t-test w/ mu = 0)</a>
  <ul class="collapse">
<li><a href="#extra-use-of-broom-package-tidy-function-w-t.test-1" id="toc-extra-use-of-broom-package-tidy-function-w-t.test-1" class="nav-link" data-scroll-target="#extra-use-of-broom-package-tidy-function-w-t.test-1">Extra: Use of broom package tidy() function w/ t.test()</a></li>
  </ul>
</li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">BIO 5100 Comparing Means from independent and paired samples</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jeremy Claisse </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">19 Apr 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header><section id="load-packages" class="level1"><h1>Load Packages</h1>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># load tidyverse packages</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># load broom package (for linear model related functions)</span></span>
<span><span class="co"># note broom package is installed as part of tidymodels package</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># load skimr package - to use skim() function for descriptive statistics</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://docs.ropensci.org/skimr/">skimr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># load emmeans "estimated marginal means" package</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/rvlenth/emmeans">emmeans</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># load cowplot package - used to combine multiple ggplots into a single figure</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://wilkelab.org/cowplot/">cowplot</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The tidyverse package is actually a collection of multiple R packages <a href="https://www.tidyverse.org/packages/" class="uri">https://www.tidyverse.org/packages/</a> including the <strong>ggplot2</strong> package (for plotting) and <strong>dplyr</strong> package (for organizing and summarizing data). And you can load these (and others packages in the tidyverse) all at once using <code><a href="https://tidyverse.tidyverse.org">library(tidyverse)</a></code>.</p>
<p>The <strong>ggplot2 Package</strong> we will use primarily for making plots (and is part of the tidyverse) has great help pages: <a href="https://ggplot2.tidyverse.org/reference/index.html" class="uri"><strong>https://ggplot2.tidyverse.org/reference/index.html</strong></a></p>
<p>The <strong>dplyr Package</strong> we will use for “data wrangling” (e.g., organizing, summarizing) and it also has (not as extensive) help pages <a href="https://dplyr.tidyverse.org/" class="uri">https://dplyr.tidyverse.org/</a> (plus cheat sheets <em>RStudio &gt; Help &gt; Cheatsheets</em>)</p>
<p>The <strong>broom Package</strong> is <strong>installed as part of <a href="https://tidymodels.org/"><u>tidymodels</u></a> meta-package</strong> (similar to tidyverse). More information/examples of broom package functions can be found here: <a href="https://broom.tidymodels.org/articles/broom.html" class="uri">https://broom.tidymodels.org/articles/broom.html</a></p>
<p>The <strong>emmeans Package</strong> will be used to output means, 95% CIs, p-values and other statistics from specified <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> objects</p>
<ul>
<li><p>Lots of vignettes here that demo what the package can do: <a href="https://cran.r-project.org/web/packages/emmeans/index.html" class="uri">https://cran.r-project.org/web/packages/emmeans/index.html</a></p></li>
<li><p>This one reviews the basics: <a href="https://cran.r-project.org/web/packages/emmeans/vignettes/AQuickStart.html" class="uri">https://cran.r-project.org/web/packages/emmeans/vignettes/AQuickStart.html</a></p></li>
</ul>
<p>The <strong>cowplot Package</strong> will be used here to combined multiple ggplots into a single figure. But it also contains functions for all sorts other plotting purposes (<em>some cool/useful, others I would not necessarily advise using</em>):</p>
<ul>
<li>cowplot <a href="https://cran.r-project.org/web/packages/cowplot/vignettes/introduction.html" class="uri">https://cran.r-project.org/web/packages/cowplot/vignettes/introduction.html</a>
</li>
</ul>
<hr></section><section id="general-modeling-strategy" class="level1"><h1>General modeling strategy:</h1>
<p>See here for an overall description of the approach from exploratory analysis to reporting results:</p>
<p><a href="https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/intro-linear-models.html#modeling-strategy" class="uri">https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/intro-linear-models.html#modeling-strategy</a></p>
<hr></section><section id="comparing-means-of-2-independent-samples" class="level1"><h1>Comparing means of 2 independent samples</h1>
<section id="linear-model-w-a-categorical-x-explanatory-variable" class="level2"><h2 class="anchored" data-anchor-id="linear-model-w-a-categorical-x-explanatory-variable">Linear model w/ a categorical X (explanatory) variable</h2>
<p>For this analysis we’ll use one of the data sets built into R:</p>
<p><code>ToothGrowth</code> (The Effect of Vitamin C on Tooth Growth in Guinea Pigs)</p>
<p>From: <em>Crampton, E. W. (1947). The growth of the odontoblast of the incisor teeth as a criterion of vitamin C intake of the guinea pig. The Journal of Nutrition, 33(5), 491-504. doi: <a href="https://academic.oup.com/jn/article-abstract/33/5/491/4726758" class="uri">https://academic.oup.com/jn/article-abstract/33/5/491/4726758</a>.</em></p>
<p><em>Note: R has many built-in data sets and a list of them can be viewed with the</em> <code><a href="https://rdrr.io/r/utils/data.html">data()</a></code> <em>function</em></p>
<p>In the <code>ToothGrowth</code> data set the <strong>response is the length</strong> of odontoblasts (cells responsible for tooth growth) in 60 guinea pigs. Each animal received one of three dose levels of vitamin C (0.5, 1, and 2 mg/day) by one of two delivery methods, orange juice or ascorbic acid (a form of vitamin C and coded as VC).</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">#Each built in data set has a help file that can be viewed:</span></span>
<span><span class="op">?</span><span class="va">ToothGrowth</span></span>
<span></span>
<span><span class="co">#View the structure of the full data set:</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">ToothGrowth</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 60
Columns: 3
$ len  &lt;dbl&gt; 4.2, 11.5, 7.3, 5.8, 6.4, 10.0, 11.2, 11.2, 5.2, 7.0, 16.5, 16.5,…
$ supp &lt;fct&gt; VC, VC, VC, VC, VC, VC, VC, VC, VC, VC, VC, VC, VC, VC, VC, VC, V…
$ dose &lt;dbl&gt; 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, …</code></pre>
</div>
</div>
<p>While the full data set has 1 numeric response (<strong><code>len</code></strong>) and 2 categorical explanatory variables (Supplement Type and Dose) <strong>we are going to reduce the data set to only one explanatory variable</strong> (<strong><code>supp</code></strong>: Supplement Type) with 2 levels (<strong><code>OJ</code></strong>: Orange Juice; <strong><code>VC</code></strong>: Ascorbic Acid) by filtering the data to select only guinea pigs that received a <code>dose == 1</code></p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat_tg</span> <span class="op">&lt;-</span> <span class="va">ToothGrowth</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">dose</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">len</span>, <span class="va">supp</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">dat_tg</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 20
Columns: 2
$ len  &lt;dbl&gt; 16.5, 16.5, 15.2, 17.3, 22.5, 17.3, 13.6, 14.5, 18.8, 15.5, 19.7,…
$ supp &lt;fct&gt; VC, VC, VC, VC, VC, VC, VC, VC, VC, VC, OJ, OJ, OJ, OJ, OJ, OJ, O…</code></pre>
</div>
</div>
<p>Biological Question: <strong>Does supplement type of vitamin C have an effect on length of odontoblasts (cells responsible for tooth growth) in guinea pigs?</strong> (<em>when given a dose level of 1 mg/day</em>)</p>
</section><section id="initial-exploratory-analysis" class="level2"><h2 class="anchored" data-anchor-id="initial-exploratory-analysis">Initial Exploratory Analysis</h2>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Individual Value Plot (Stripchart) length by supplement type</span></span>
<span><span class="va">dat_tg</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">supp</span>, y <span class="op">=</span> <span class="va">len</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Compare_means_independent_paried_samples_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Histogram of length faceted by supplement type</span></span>
<span><span class="va">dat_tg</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">len</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">6</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_grid.html">facet_grid</a></span><span class="op">(</span>rows <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/vars.html">vars</a></span><span class="op">(</span><span class="va">supp</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Compare_means_independent_paried_samples_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Boxplots of length by supplement type</span></span>
<span><span class="va">dat_tg</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">supp</span>, y <span class="op">=</span> <span class="va">len</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Compare_means_independent_paried_samples_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># summary/descriptive statistics of length by supplement type</span></span>
<span><span class="va">dat_tg</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">supp</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://docs.ropensci.org/skimr/reference/skim.html">skim</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">group_by(dat_tg, supp)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">supp</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 5%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 6%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: left;">supp</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">len</td>
<td style="text-align: left;">OJ</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">22.70</td>
<td style="text-align: right;">3.91</td>
<td style="text-align: right;">14.5</td>
<td style="text-align: right;">20.30</td>
<td style="text-align: right;">23.45</td>
<td style="text-align: right;">25.65</td>
<td style="text-align: right;">27.3</td>
<td style="text-align: left;">▂▁▆▃▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">len</td>
<td style="text-align: left;">VC</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">16.77</td>
<td style="text-align: right;">2.52</td>
<td style="text-align: right;">13.6</td>
<td style="text-align: right;">15.27</td>
<td style="text-align: right;">16.50</td>
<td style="text-align: right;">17.30</td>
<td style="text-align: right;">22.5</td>
<td style="text-align: left;">▇▇▇▁▂</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="checking-assumptions" class="level2"><h2 class="anchored" data-anchor-id="checking-assumptions">Checking assumptions</h2>
<p><strong>Linear model assumptions:</strong></p>
<p>More details/descriptions can be found here:</p>
<p><a href="https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/intro-linear-models.html#specific-assumptions-for-inference-with-a-linear-model" class="uri">https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/intro-linear-models.html#specific-assumptions-for-inference-with-a-linear-model</a></p>
<p>t-test assumptions are also described in (<em>way too much</em>) detail here: <a href="https://en.wikipedia.org/wiki/Student%27s_t-test#Assumptions" class="uri">https://en.wikipedia.org/wiki/Student%27s_t-test#Assumptions</a></p>
<p><em>The most relevant are:</em></p>
<ul>
<li>data are independent (<em>e.g., not paired, grouped, or otherwise related by some other factor that the grouping variable already in your model</em>), collected with a random sampling approach</li>
<li>model residuals are normally distributed</li>
<li>Constant or “equal” variance or homoskedasticity</li>
</ul>
<section id="in-practical-terms-just-check-to-make-sure-during-exploratory-analysis" class="level3"><h3 class="anchored" data-anchor-id="in-practical-terms-just-check-to-make-sure-during-exploratory-analysis">In practical terms just check to make sure during exploratory analysis:</h3>
<ol type="1">
<li><strong>there are <u>no</u> “large” outliers</strong></li>
<li>
<strong>the distributions of each group are <u>not</u> highly skewed or bimodal</strong> (<em>although this is often hard to judge at small sample sizes</em>)</li>
<li>Check for <strong>“equal” variances among groups (<em>homoscedasticity</em>)</strong>
</li>
</ol>
<ul>
<li>This assumption says that all groups (samples) of data have “the same” variance (e.g., spread, sd), but in terms of checking it’s about making sure the standard deviations are not too different from each other.</li>
</ul>
<p>First look at plots above (histogram, boxplot, individual value plot): <strong><em>Does the spread look similar in 2 samples?</em></strong></p>
<p>Then assess equal variance assumption with a “<em>rule of thumb</em>”:</p>
<ul>
<li>
<strong>Primary rule:</strong> (<em>When n/group &gt; 5 &amp; n/groups similar</em>) Consider alternative approach if largest sd &gt; 4*smallest sd (<em>i.e., variances not similar enough</em>)</li>
<li>
<strong>Secondary Rule:</strong> (<em>When n/group NOT similar</em>) Be extra cautious when largest sd is associated with the group with the smallest n.&nbsp;In this case consider alternative approach if largest sd &gt; 2*smallest sd.</li>
<li>see <a href="https://csu-cpp.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma991004980729702915&amp;context=L&amp;vid=01CALS_PUP:01CALS_PUP&amp;lang=en&amp;search_scope=everything&amp;adaptor=Local%20Search%20Engine&amp;tab=Everything&amp;query=any,contains,Biostatistical%20Analysis%20%20Jerrold%20H.%20Zar&amp;offset=0">Zar <strong>Biostatistical Analysis</strong> textbook</a> for more info (<em>and/or could cite in thesis/paper if necessary</em>)</li>
</ul>
<p><u><em>If there are large outliers, one/both of the distributions are very highly skewed, and/or the spread in the data is very different between groups</em></u><em>, then can consider other options for calculating the 95% CIs (e.g., bootstrapping), using a Generalized linear model, and/or running a non-parametric test.</em></p>
</section></section><section id="descriptive-statistics-for-comparing-two-groups" class="level2"><h2 class="anchored" data-anchor-id="descriptive-statistics-for-comparing-two-groups">Descriptive Statistics for comparing two groups</h2>
<p><strong>For EACH GROUP (SAMPLE) of numerical response variable length we’ll calculate:</strong></p>
<ul>
<li><p><strong>mean</strong>: <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code></p></li>
<li><p><strong>standard deviation</strong> (<strong><em>spread in data</em></strong>): <code><a href="https://rdrr.io/r/stats/sd.html">sd()</a></code></p></li>
<li><p><strong>sample size</strong>: <code><a href="https://dplyr.tidyverse.org/reference/context.html">n()</a></code></p></li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat_tg</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">supp</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span></span>
<span>    mean_length <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">len</span><span class="op">)</span>,</span>
<span>    sd_length <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">len</span><span class="op">)</span>,</span>
<span>    n_length <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  supp  mean_length sd_length n_length
  &lt;fct&gt;       &lt;dbl&gt;     &lt;dbl&gt;    &lt;int&gt;
1 OJ           22.7      3.91       10
2 VC           16.8      2.52       10</code></pre>
</div>
</div>
</section><section id="magnitude-of-the-effect-size" class="level2"><h2 class="anchored" data-anchor-id="magnitude-of-the-effect-size">Magnitude of the effect size</h2>
<p>We can then pull values from the calculated statistics above to make an additional calculation of the <strong>magnitude of the effect size</strong> (i.e., <em>how different are the 2 means?</em>)</p>
<ul>
<li><p><strong>effect size</strong> (difference between the means)</p></li>
<li><p>effect size as a <strong>percent</strong> difference (difference between the means/smaller mean * 100)</p></li>
<li><p><em>Note: “<strong>Direction</strong>” of effect size in this instance refers to indicating which mean is larger.</em></p></li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># effect size: mean OJ - mean VC</span></span>
<span><span class="fl">22.7</span><span class="op">-</span><span class="fl">16.8</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.9</code></pre>
</div>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># effect size expressed as percentage difference</span></span>
<span><span class="co"># use round() function to round to 0 decimal places</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="op">(</span><span class="fl">22.7</span><span class="op">-</span><span class="fl">16.8</span><span class="op">)</span><span class="op">/</span><span class="fl">16.8</span><span class="op">*</span><span class="fl">100</span>, <span class="fl">0</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35</code></pre>
</div>
</div>
</section><section id="fit-linear-model" class="level2"><h2 class="anchored" data-anchor-id="fit-linear-model">Fit linear model</h2>
<p>Note this code/process is adapted from: <a href="https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/oneway.html#oneway" class="uri">https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/oneway.html#oneway</a></p>
<ul>
<li><em>If you want more background, detailed explanation or need to do a more complicated analysis, that is a great resource.</em></li>
</ul>
<p><strong>Fit the linear model (numerical response w/ 1 categorical X value)</strong></p>
<ul>
<li>in <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> formula:
<ul>
<li><p>Y ~ X</p></li>
<li><p>Response (<em>numeric variable</em>) ~ Explanatory (<em>in this case a categorical variable</em>)</p></li>
</ul>
</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_len_supp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">len</span> <span class="op">~</span> <span class="va">supp</span>, data <span class="op">=</span> <span class="va">dat_tg</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lm_len_supp</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = len ~ supp, data = dat_tg)

Coefficients:
(Intercept)       suppVC  
      22.70        -5.93  </code></pre>
</div>
</div>
<section id="coefficient-table" class="level3"><h3 class="anchored" data-anchor-id="coefficient-table">Coefficient table</h3>
<p>Create a “coefficient table” in a “tidy” table format using <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> function from broom package, with a <code>conf.int = T</code> argument to include calculation of 95% CIs.</p>
<ul>
<li><em>Note: the coefficient table is not the most useful/friendly format and can include some irrelevant information. While it is a good idea to create and review it, you will mostly use/interpret the emmeans and contrast (pairs) tables below.</em></li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># use tidy function from broom package with the linear model object</span></span>
<span><span class="va">lm_len_supp_coef</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">lm_len_supp</span>, conf.int <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lm_len_supp_coef</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 7
  term        estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    22.7       1.04     21.8  2.11e-14    20.5      24.9 
2 suppVC         -5.93      1.47     -4.03 7.81e- 4    -9.02     -2.84</code></pre>
</div>
</div>
</section></section><section id="create-emmeans-table" class="level2"><h2 class="anchored" data-anchor-id="create-emmeans-table">Create emmeans table</h2>
<p>Using <code><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans()</a></code> function from the <strong>emmeans package</strong></p>
<ul>
<li><p>Provides the basics: <a href="https://cran.r-project.org/web/packages/emmeans/vignettes/AQuickStart.html" class="uri">https://cran.r-project.org/web/packages/emmeans/vignettes/AQuickStart.html</a></p></li>
<li><p>&amp; Lots of vignettes for other uses of functions in this package: <a href="https://cran.r-project.org/web/packages/emmeans/index.html" class="uri">https://cran.r-project.org/web/packages/emmeans/index.html</a></p></li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># create emmeans table object</span></span>
<span><span class="va">lm_len_supp_emm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">lm_len_supp</span>, <span class="op">~</span> <span class="va">supp</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lm_len_supp_emm</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> supp emmean   SE df lower.CL upper.CL
 OJ     22.7 1.04 18     20.5     24.9
 VC     16.8 1.04 18     14.6     19.0

Confidence level used: 0.95 </code></pre>
</div>
</div>
<ul>
<li><p><strong>The means (emmean column) in the emmeans table</strong> are technically “modeled” means, but here, and for many linear models, these will be equal to the sampled means (the means calculated from each group of raw data). This may not be the case for some more complicated models.</p></li>
<li>
<p><strong>The 95% CIs in the emmeans table</strong> (lower.CL to upper.CL) are calculated using all the data in the model (using a pooled standard deviation and sample size across both groups of data). You’ll notice they both have the same size:</p>
<ul>
<li><p>OJ: 20.5 to 24.9 = 4.4</p></li>
<li><p>VC: 14.6 to 19.0 = 4.4</p></li>
<li><p><em>If 95% CIs were calculated using just the OJ (or VC) data for each mean individually they would be different sizes.</em></p></li>
</ul>
</li>
</ul>
<p>For more explanation see: <a href="https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/oneway.html#the-emmeans-table-is-a-table-of-modeled-means-and-inferential-statistics" class="uri">https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/oneway.html#the-emmeans-table-is-a-table-of-modeled-means-and-inferential-statistics</a></p>
</section><section id="points-means-plot-w-model-95-cis" class="level2"><h2 class="anchored" data-anchor-id="points-means-plot-w-model-95-cis">Points &amp; means plot w/ (model) 95% CIs</h2>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># note in ggplot below we had to turn the emmeans object into a tibble (data.frame) so it would work as data in ggplot</span></span>
<span><span class="co"># as_tibble(lm_len_supp_emm)</span></span>
<span></span>
<span><span class="va">plot_lm_len_supp_emm</span> <span class="op">&lt;-</span> <span class="va">dat_tg</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">supp</span>, y <span class="op">=</span> <span class="va">len</span>, color <span class="op">=</span> <span class="va">supp</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Length of Odontoblasts (μm)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Supplement Type"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co">#use emm object as 2nd data table to plot 95% CIs</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_crossbar</a></span><span class="op">(</span></span>
<span>    data <span class="op">=</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="va">lm_len_supp_emm</span><span class="op">)</span>,</span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">emmean</span>,</span>
<span>        ymin <span class="op">=</span> <span class="va">lower.CL</span>,</span>
<span>        ymax <span class="op">=</span> <span class="va">upper.CL</span><span class="op">)</span>,</span>
<span>    width <span class="op">=</span> <span class="fl">0.1</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">plot_lm_len_supp_emm</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Compare_means_independent_paried_samples_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="288"></p>
</div>
</div>
<p>This plot shows the raw data for each group (OJ, VC) as points. The <code><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_crossbar()</a></code> plots the group means (middle line) and the 95% CIs from the associated linear model which were calculated in the emmeans table above.</p>
<ul>
<li>Note <code><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_pointrange()</a></code> could be used instead of <code><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_crossbar()</a></code> if you prefer that style of plotting mean + CIs <a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html" class="uri">https://ggplot2.tidyverse.org/reference/geom_linerange.html</a> (scroll down to bottom of page to see various examples of ways to plot error bars around a mean)</li>
</ul></section><section id="contrasts-table-corresponding-effects-plot" class="level2"><h2 class="anchored" data-anchor-id="contrasts-table-corresponding-effects-plot">Contrasts table &amp; corresponding “effects” plot</h2>
<p><strong>“Contrasts table”</strong> using <code><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast()</a></code> function from <strong>emmeans package</strong></p>
<ul>
<li>For details on the argument <code>method =</code> see help(“contrast-methods”)</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_len_supp_pairs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/contrast.html">contrast</a></span><span class="op">(</span><span class="va">lm_len_supp_emm</span>,</span>
<span>                            method <span class="op">=</span> <span class="st">"pairwise"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span>infer <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co"># Note: method = "revpairwise" switches the order in subtraction for comparison </span></span>
<span><span class="co"># (up to researcher/you to determine which is more appropriate)</span></span>
<span></span>
<span><span class="va">lm_len_supp_pairs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast estimate   SE df lower.CL upper.CL t.ratio p.value
 OJ - VC      5.93 1.47 18     2.84     9.02   4.033  0.0008

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>This table is important for reporting treatment effect and 95% CI and the object <code>lm_len_supp_pairs</code> is used in the ggplot code below to create the effects plot.</p>
<ul>
<li>A <strong>contrast</strong> is a difference in means.</li>
<li>The <strong>“estimate” column</strong> is this difference</li>
<li>
<strong>95% CI of this difference</strong> is lower.CL to upper.CL</li>
<li>The columns “t.ratio” and “p.value” contains the t (test statistic) and p values of the significance test of the estimate. The t-statistic is the ratio of the estimate (difference in means) to the SE of the estimate (which includes sd, the spread in the data, and the sample size). It is a signal (the estimate) to noise (SE of the estimate) ratio.</li>
<li>The p-value here can also be reported in your results, it is for the significance test: <em>is the difference between the 2 means significantly different from 0?</em>
<ul>
<li>Or a better interpretation of the p-value here is: <em>what is the probability of getting this data if there was no difference between the 2 means?</em>
</li>
<li>And interpret it as a %: <em>There is only a 0.08% chance that these data came from a true population where there was no difference between the 2 means.</em>
</li>
</ul>
</li>
</ul>
<p>For more explanation see: <a href="https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/oneway.html#estimates-of-the-effects-are-in-the-contrasts-table" class="uri">https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/oneway.html#estimates-of-the-effects-are-in-the-contrasts-table</a></p>
</section><section id="effects-plot-w-95-ci" class="level2"><h2 class="anchored" data-anchor-id="effects-plot-w-95-ci">Effects plot w/ 95% CI</h2>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># NOTE: in ggplot code below we had to turn the contrast object into </span></span>
<span><span class="co"># a tibble (data.frame) so it would work as data in ggplot</span></span>
<span></span>
<span><span class="va">plot_lm_len_supp_pairs</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="va">lm_len_supp_pairs</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>y <span class="op">=</span> <span class="va">contrast</span>, x <span class="op">=</span> <span class="va">estimate</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_pointrange</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>xmin <span class="op">=</span> <span class="va">lower.CL</span>,</span>
<span>                      xmax <span class="op">=</span> <span class="va">upper.CL</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fl">0</span>, linetype <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Effects (μm)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">""</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"top"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">plot_lm_len_supp_pairs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Compare_means_independent_paried_samples_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="288"></p>
</div>
</div>
<p>This plot shows the difference between the 2 means (OJ mean - VC mean = 5.9), and the 95% CI for that difference (i.e., <em>“if the experiment was repeated, 95% of the time you’d expect the true population mean of the difference between OJ and VC to be between 2.8 and 9.0”</em>).</p>
<ul>
<li>The dashed line at 0 is there for reference since if the OJ and VC treatments produced the same tooth cell growth, the difference in their means would be 0.</li>
</ul></section><section id="combine-plots-into-a-single-results-figure" class="level2"><h2 class="anchored" data-anchor-id="combine-plots-into-a-single-results-figure">Combine plots into a single results figure</h2>
<p>We’ll use the <code><a href="https://wilkelab.org/cowplot/reference/plot_grid.html">plot_grid()</a></code> function from the <strong>cowplot package</strong> to combine our two plots above into a single results figure.</p>
<ul>
<li>The <code>align = "v"</code> and <code>axis = "rl"</code> arguments make the axes of our 2 plots line up appropriately when combined. See help file for more detail: <a href="https://rdrr.io/cran/cowplot/man/plot_grid.html" class="uri">https://rdrr.io/cran/cowplot/man/plot_grid.html</a>
</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">results_plot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/plot_grid.html">plot_grid</a></span><span class="op">(</span><span class="va">plot_lm_len_supp_pairs</span>, </span>
<span>                          <span class="va">plot_lm_len_supp_emm</span>, </span>
<span>                          nrow <span class="op">=</span> <span class="fl">2</span>,</span>
<span>                          align <span class="op">=</span> <span class="st">"v"</span>,</span>
<span>                          axis <span class="op">=</span> <span class="st">"rl"</span>,</span>
<span>                          rel_heights <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.25</span>, <span class="fl">1</span><span class="op">)</span></span>
<span>                          <span class="op">)</span></span>
<span><span class="co"># rel_heights argument specifies relative size of two plots (i.e., first plot is 0.25 as tall as the second plot) </span></span>
<span></span>
<span><span class="va">results_plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Compare_means_independent_paried_samples_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="288"></p>
</div>
</div>
<p>This primary results plot is adapted from code in (the version you are using is based on regular ggplot code): <a href="https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/oneway.html#step-6-plot-the-model" class="uri">https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/oneway.html#step-6-plot-the-model</a></p>
</section><section id="export-save-plot-to-a-.png-file-with-ggsave" class="level2"><h2 class="anchored" data-anchor-id="export-save-plot-to-a-.png-file-with-ggsave">Export (save) plot to a .png file with ggsave()</h2>
<ul>
<li><p>the file will be saved to your “working directory” (typically <u>the folder where your .qmd file is</u>). <strong>You’ll need to look in that folder to see the .png file</strong></p></li>
<li><p><strong>You identify the type of file format you want to save it to with the <u>file name extension</u> at the end of the file name</strong>. Here we use <strong>.png</strong> (a great default for putting images into word docs or PPT presentations). But many others are available such as: “.pdf” (easy to view or email a .pdf to someone; and good to use for uploading plot files to journals if they’ll accept this format), “.eps” (another vector format some journals one), “.png”, “.jpeg”, “.tiff”, “.svg”(use for further editing in <a href="https://inkscape.org/" class="uri">https://inkscape.org/</a> freeware on windows).</p></li>
<li><p>You can read more about the difference between <strong><em>vector vs.&nbsp;raster</em></strong> image file types here: <a href="https://guides.lib.umich.edu/c.php?g=282942&amp;p=1885352" class="uri">https://guides.lib.umich.edu/c.php?g=282942&amp;p=1885352</a>. And more about specific file types here: <a href="https://guides.lib.umich.edu/c.php?g=282942&amp;p=1885348" class="uri">https://guides.lib.umich.edu/c.php?g=282942&amp;p=1885348</a></p></li>
<li><p>You specify the dimensions of the plot with the <code>width =</code> and <code>height =</code> arguments, default is inches. Try different widths and heights (<em>keeping in mind what would fit on a 8in by 11in page size</em>) and see what works for the plot you making. Often a plot shows the data better when it is taller or wider (<strong><em>so try different ratios of width to height</em></strong>).</p></li>
<li><p>You can also specify the image “quality” using the “dots per inch” argument <code>dpi =</code> and typically you want to use 300 or 600 for a high quality image. Depending on the file type (with .tiff for example) 600 dpi can sometimes create huge file sizes, but that is usually where I start (<em>then only go down to 300 if needed</em>).</p></li>
<li><p><em>NOTE - sometimes you can get an error when running <code><a href="https://ggplot2.tidyverse.org/reference/ggsave.html">ggsave()</a></code> repeatedly if the saved .png file is already open on your computer in your image viewer - need to close it each time you want to edit and re-output the image file.</em></p></li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># output plot to .png file type, set size (default is inches), 300 or 600 dpi is high quality</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsave.html">ggsave</a></span><span class="op">(</span></span>
<span>  <span class="st">"plot_len_by_supp_95CIs.png"</span>,</span>
<span>  <span class="va">results_plot</span>,</span>
<span>  width <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  height <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  dpi <span class="op">=</span> <span class="fl">600</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="results-sentence" class="level2"><h2 class="anchored" data-anchor-id="results-sentence">Results sentence:</h2>
<p>Using statistics produced in the code chunks above we can write:</p>
<p>Mean length of odontoblasts that received vitamin C from orange juice (mean length: 22.7 <em>μm</em>, 95% CI: 20.5 to 24.9) was 35% higher (mean difference: 5.9 <em>μm</em> , 95% CI: 2.84 to 9.02, p = 0.0008) than those that received vitamin C from an ascorbic acid supplement (mean length: 16.8 <em>μm</em>, 95% CI: 14.6 to 19.0) (Fig. X).</p>
<p>Note:</p>
<ol type="1">
<li><p><em>(Fig. X) would be citing the combined results figure that includes (top) the effects plot and (below) plot w/ the data points, means and the 95% CIs for each group.</em></p></li>
<li><p><em>You can add the t-statistic and p-value (from the contrasts table) above or two-sample t-test output below, both are equivalent.</em></p></li>
</ol>
<p>More explanation of why it is optional to (and advised by this author that you don’t) use the word “significant” in the results can be found here (<em>but if you or your adviser want to, that is fine too, since p-value is &lt; 0.05</em>) and examples of writing results can be found here: <a href="https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/oneway.html#step-7-report-the-model-results" class="uri">https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/oneway.html#step-7-report-the-model-results</a></p>
</section><section id="two-sample-t-test-hypothesis-test" class="level2"><h2 class="anchored" data-anchor-id="two-sample-t-test-hypothesis-test">Two-sample t-test (hypothesis test)</h2>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Review the help file for the t.test function, there are various options</span></span>
<span><span class="op">?</span><span class="va">t.test</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Statistical Hypotheses (for a two-sample t-test)</strong></p>
<p><em>Null Hypothesis</em>: there is <strong>no difference</strong> (<em>i.e., they are equal</em>) in the population mean lengths of the guinea pigs that received vitamin C through orange juice and ascorbic acid supplements.</p>
<p><em>Alternative Hypothesis</em>: there is <strong>a difference</strong> (<em>i.e., they are not equal</em>) in the population mean lengths of the guinea pigs that received vitamin C through orange juice and ascorbic acid supplements.</p>
<hr>
<section id="welchs-t-test-is-default-that-the-t.test-function-in-r-runs" class="level3"><h3 class="anchored" data-anchor-id="welchs-t-test-is-default-that-the-t.test-function-in-r-runs">Welch’s t-test is default that the <code>t.test()</code> function in R runs</h3>
<ul>
<li>
<strong>Welch’s t-test <u>does NOT assume equal variances</u> (</strong><em>so you do not need to worry about that assumption of the regular/typical Student’s t-test)</em>
</li>
<li><a href="https://en.wikipedia.org/wiki/Welch%27s_t-test" class="uri">https://en.wikipedia.org/wiki/Welch%27s_t-test</a></li>
<li>It defines the statistic <em>t</em> slightly differently, unlike in Student’s t-test, the denominator is not based on a pooled variance estimate.</li>
<li>It is not recommended to pre-test for equal variances and then choose between Student’s t-test or Welch’s t-test [5]. Rather, Welch’s t-test can be applied directly and without any substantial disadvantages to Student’s t-test as noted above. Welch’s t-test remains robust for skewed distributions at large sample sizes.[6] Reliability decreases for skewed distributions and smaller samples.</li>
<li>[5] Zimmerman, D. W. (2004). “A note on preliminary tests of equality of variances”. British Journal of Mathematical and Statistical Psychology. 57: 173–181.</li>
<li>[6] Fagerland, M. W. (2012). “t-tests, non-parametric tests, and large studies—a paradox of statistical practice?”. BioMed Central Medical Research Methodology. 12: 78. <a href="doi:10.1186/1471-2288-12-78" class="uri">doi:10.1186/1471-2288-12-78</a>.</li>
</ul>
<p>Use a formula within <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> and your data object with <code>data =</code> argument.</p>
<ul>
<li>
<strong>response ~ explanatory</strong> (here: <em>length as a function of supplement type</em>)</li>
<li>By default it runs a two-tailed test.</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># run default arguments (two-tailed test and assume un-equal variances, with Welch's correction)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">len</span> <span class="op">~</span> <span class="va">supp</span>, data <span class="op">=</span> <span class="va">dat_tg</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  len by supp
t = 4.0328, df = 15.358, p-value = 0.001038
alternative hypothesis: true difference in means between group OJ and group VC is not equal to 0
95 percent confidence interval:
 2.802148 9.057852
sample estimates:
mean in group OJ mean in group VC 
           22.70            16.77 </code></pre>
</div>
</div>
<p>This p-value is slightly larger than the one calculated in the contrasts table above because it is adjusted larger in this “Welch’s” t-test as part of the process of not needed to assume equal variances.</p>
<p><em>Also note: the 95% CI the t.test() function outputs is the 95% CI of the difference between the two means (i.e., <strong>the effect size</strong>): mean OJ - mean VC = 5.9 (95% CI: 2.8 to 9.1).</em></p>
<p><em>In words: if the experiment was repeated, 95% of the time you’d expect the true population mean of the difference to be between 2.8 and 9.1 (length). Because this does not include 0, it by itself can be interpreted as a “significant result.”</em></p>
<hr></section><section id="extra-use-of-broom-package-tidy-function-w-t.test" class="level3"><h3 class="anchored" data-anchor-id="extra-use-of-broom-package-tidy-function-w-t.test">Extra: Use of broom package tidy() function w/ t.test()</h3>
<ul>
<li><p>Can also wrap the <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> function from broom package around the t.test, to get a “tidy” output with the same values organized in a data.frame</p></li>
<li><p>Can be useful if you want to store the results and directly output values (like p-value or CIs etc.)</p></li>
</ul>
<p><a href="https://cran.r-project.org/web/packages/broom/vignettes/broom.html" class="uri">https://cran.r-project.org/web/packages/broom/vignettes/broom.html</a></p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">t_test_len_supp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">len</span> <span class="op">~</span> <span class="va">supp</span>, data <span class="op">=</span> <span class="va">dat_tg</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># show results in "tidy" data.frame format (from broom package)</span></span>
<span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">t_test_len_supp</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 10
  estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high
     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1     5.93      22.7      16.8      4.03 0.00104      15.4     2.80      9.06
# ℹ 2 more variables: method &lt;chr&gt;, alternative &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># select mean difference, 95%CIs and p-value</span></span>
<span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">t_test_len_supp</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">estimate</span>, <span class="va">conf.low</span>, <span class="va">conf.high</span>, <span class="va">p.value</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  estimate conf.low conf.high p.value
     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1     5.93     2.80      9.06 0.00104</code></pre>
</div>
</div>
<hr></section></section></section><section id="paired-sample-matched-pair-experiment-mean-comparison" class="level1"><h1>Paired-sample (matched pair) experiment mean comparison</h1>
<section id="biological-question-does-a-drug-have-an-effect-on-patient-cell-counts" class="level4"><h4 class="anchored" data-anchor-id="biological-question-does-a-drug-have-an-effect-on-patient-cell-counts"><strong>Biological Question: Does a drug have an effect on patient cell counts?</strong></h4>
<p><strong>Manually entered <em>made-up</em> data in “wide” format for this demo, then converted to long more “tidy” format (NOT part of typical analysis procedure)</strong></p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co">## Made-up data for this demo, manually entered into </span></span>
<span><span class="co"># dataframe</span></span>
<span><span class="co"># NOTE - This is just for demo, not part of typical </span></span>
<span><span class="co"># analysis where you'd already have your data entered</span></span>
<span><span class="co"># in tidy format in a spreadsheet and read that in.</span></span>
<span><span class="va">dat_paired_wide</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  patient_no <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">9</span>,</span>
<span>  placebo <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">78</span>, <span class="fl">54</span>, <span class="fl">142</span>, <span class="fl">25</span>, <span class="fl">101</span>, <span class="fl">99</span>, <span class="fl">94</span>, <span class="fl">107</span>, <span class="fl">64</span><span class="op">)</span>,</span>
<span>  drug <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">79</span>, <span class="fl">48</span>, <span class="fl">52</span>, <span class="fl">15</span>, <span class="fl">61</span>, <span class="fl">107</span>, <span class="fl">77</span>, <span class="fl">54</span>, <span class="fl">5</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="co">## use pivot_longer function from dplyr to convert from wide to long data table format</span></span>
<span><span class="va">dat_paired</span> <span class="op">&lt;-</span> <span class="va">dat_paired_wide</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>cols <span class="op">=</span> <span class="va">placebo</span><span class="op">:</span><span class="va">drug</span>, </span>
<span>               names_to <span class="op">=</span> <span class="st">"treatment"</span>, values_to <span class="op">=</span> <span class="st">"cell_count"</span><span class="op">)</span></span>
<span><span class="co"># data now in "long" format </span></span>
<span><span class="co"># i.e., what you always want your data to be if possible</span></span>
<span><span class="co"># and typically need long format for plotting w/ ggplot</span></span>
<span><span class="co"># single variable in each column</span></span>
<span><span class="va">dat_paired</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 3
   patient_no treatment cell_count
        &lt;int&gt; &lt;chr&gt;          &lt;dbl&gt;
 1          1 placebo           78
 2          1 drug              79
 3          2 placebo           54
 4          2 drug              48
 5          3 placebo          142
 6          3 drug              52
 7          4 placebo           25
 8          4 drug              15
 9          5 placebo          101
10          5 drug              61
11          6 placebo           99
12          6 drug             107
13          7 placebo           94
14          7 drug              77
15          8 placebo          107
16          8 drug              54
17          9 placebo           64
18          9 drug               5</code></pre>
</div>
</div>
<p><em>In output above can see the data are “paired” by patient_no.</em></p>
<ul>
<li>use glimpse<code>()</code> function to examine the structure of the data.frame named dat_yt</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">dat_paired</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 18
Columns: 3
$ patient_no &lt;int&gt; 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9
$ treatment  &lt;chr&gt; "placebo", "drug", "placebo", "drug", "placebo", "drug", "p…
$ cell_count &lt;dbl&gt; 78, 79, 54, 48, 142, 52, 25, 15, 101, 61, 99, 107, 94, 77, …</code></pre>
</div>
</div>
</section><section id="use-factor-function-to-covert-numeric-or-character-to-a-factor" class="level2"><h2 class="anchored" data-anchor-id="use-factor-function-to-covert-numeric-or-character-to-a-factor">Use <code>factor()</code> function to covert numeric or character to a factor</h2>
<ul>
<li>Change <code>patient_no</code> (which was by default set as numeric) to a factor since the numbers are just labels for each person, and could as easily been patient A, B, C… or their names used,</li>
<li>Change <code>count_type</code> to a factor, <em>with levels</em> (to specify the order of the two levels: <em>placebo</em>, then <em>drug</em> for plotting). Otherwise it would default to alphabetical order, with <em>drug</em> before <em>placebo</em>. In this case there’s no right or wrong order, really up to researcher preference.</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat_paired</span> <span class="op">&lt;-</span> <span class="va">dat_paired</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>patient_no <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">patient_no</span><span class="op">)</span>,</span>
<span>         treatment <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">treatment</span>,</span>
<span>                            levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"placebo"</span>, <span class="st">"drug"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># look at the data again</span></span>
<span><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">dat_paired</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 18
Columns: 3
$ patient_no &lt;fct&gt; 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9
$ treatment  &lt;fct&gt; placebo, drug, placebo, drug, placebo, drug, placebo, drug,…
$ cell_count &lt;dbl&gt; 78, 79, 54, 48, 142, 52, 25, 15, 101, 61, 99, 107, 94, 77, …</code></pre>
</div>
</div>
<p><em>In the glimpse output, you can see that <code>patient_no</code> and <code>treatment</code> are now factors.</em></p>
</section><section id="initial-exploratory-analysis-for-paired-data" class="level2"><h2 class="anchored" data-anchor-id="initial-exploratory-analysis-for-paired-data">Initial Exploratory Analysis (for Paired Data)</h2>
<p>Exploratory Analysis of cell_count by treatment:</p>
<p>Recognizing that these are paired data, we first want to see how much variability there was across individuals (<em>for example, if some patients just had naturally higher or lower cell counts</em>). Using a paired analysis design would then help us remove this additional variability due the to the patient, and better isolate just the effect of the drug.</p>
<p><strong>Create an individual value plot</strong></p>
<ul>
<li>color points by patient number (<em>note for this to work, patient number must be a factor - converted in code chunk above</em>)</li>
<li>Add lines connecting the pairs of points using the <code>group =</code> argument in within <code><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes()</a></code>in <code><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line()</a></code>
</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># note in a code chunk above treatment and patient_no were </span></span>
<span><span class="co"># already converted to factors in a code chunk above, and </span></span>
<span><span class="co"># therefore ggplot treats them accordingly.</span></span>
<span></span>
<span><span class="va">plot_dat_paired</span> <span class="op">&lt;-</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">dat_paired</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">treatment</span>, y <span class="op">=</span> <span class="va">cell_count</span>,</span>
<span>                         color <span class="op">=</span> <span class="va">patient_no</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>group <span class="op">=</span> <span class="va">patient_no</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Cell Count"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="va">plot_dat_paired</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Compare_means_independent_paried_samples_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p>The drug appears to have an effect, lower cell counts relative to the placebo, in most, but not all individuals. This effect varies from person to person (<em>i.e., some cell counts decrease a lot, some very little or even increase slightly</em>)</p></li>
<li><p>There is a lot of variability in overall cell counts among patients (ranging from 25 to over 125 for placebo, and similar for drug). This “patient-to-patient” variability is what we’ll try to account for (remove) by converting these data to differences since this is a paired experimental design.</p></li>
</ul></section><section id="convert-paired-data-to-differences-between-pairs" class="level2"><h2 class="anchored" data-anchor-id="convert-paired-data-to-differences-between-pairs">Convert Paired Data to Differences (between pairs)</h2>
<ul>
<li>create a new version the data table named <code>dat_diff</code> starting from <code>dat_paired</code>
</li>
<li>use <code><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider()</a></code> to put each treatment in its own column</li>
<li>then <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> to add a column named <code>cell_count_diff</code> which is the difference between the two treatments: <code>drug - placebo</code>
<ul>
<li><em>Note: subtraction can be done in either order - BUT you always must know what the order is to properly interpret the differences (i.e., in this case a negative difference means the placebo value was larger than the drug value, so the drug lowered the cell counts)</em></li>
</ul>
</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># convert from long to wide format, then subtract drug - placebo values </span></span>
<span><span class="co"># for each patient creating a new column named cell_count_diff</span></span>
<span><span class="va">dat_diff</span> <span class="op">&lt;-</span> <span class="va">dat_paired</span> <span class="op">|&gt;</span></span>
<span>  <span class="co"># select just columns you want to be involved in pivot</span></span>
<span>  <span class="co"># don't include extra numeric data columns</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">patient_no</span>, <span class="va">treatment</span>, <span class="va">cell_count</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider</a></span><span class="op">(</span>names_from <span class="op">=</span> <span class="va">treatment</span>,</span>
<span>              values_from <span class="op">=</span> <span class="va">cell_count</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>cell_count_diff <span class="op">=</span> <span class="va">drug</span> <span class="op">-</span> <span class="va">placebo</span><span class="op">)</span></span>
<span></span>
<span><span class="va">dat_diff</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 4
  patient_no placebo  drug cell_count_diff
  &lt;fct&gt;        &lt;dbl&gt; &lt;dbl&gt;           &lt;dbl&gt;
1 1               78    79               1
2 2               54    48              -6
3 3              142    52             -90
4 4               25    15             -10
5 5              101    61             -40
6 6               99   107               8
7 7               94    77             -17
8 8              107    54             -53
9 9               64     5             -59</code></pre>
</div>
</div>
</section><section id="exploratory-analysis-with-the-difference-values" class="level2"><h2 class="anchored" data-anchor-id="exploratory-analysis-with-the-difference-values">Exploratory analysis with the difference values</h2>
<p>Since the primary data we’ll be using for the rest of the analysis is the differences (drug - placebo) we’ll do the regular exploratory analyses with the differences:</p>
<ul>
<li>Individual Value Plot (Stripchart)</li>
<li>Histogram</li>
<li>Boxplot</li>
<li>skim() descriptive statistics</li>
</ul>
<p><em>And a horizontal or vertical line is added to represent the 0 value we want to compare our data to (to be an effect one way or the other the mean difference needs to be higher or lower than 0)</em></p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Individual Value Plot (Stripchart)</span></span>
<span><span class="co"># add a horizontal line at 0</span></span>
<span><span class="va">dat_diff</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">1</span>, y <span class="op">=</span> <span class="va">cell_count_diff</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Compare_means_independent_paried_samples_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Histogram of cell_count_diff</span></span>
<span><span class="va">dat_diff</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">cell_count_diff</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">8</span><span class="op">)</span>  <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fl">0</span>, color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Compare_means_independent_paried_samples_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Boxplot of cell_count_diff</span></span>
<span><span class="va">dat_diff</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">1</span>, y <span class="op">=</span> <span class="va">cell_count_diff</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, color <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Compare_means_independent_paried_samples_files/figure-html/unnamed-chunk-23-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># summary/descriptive statistics of cell_count_diff</span></span>
<span><span class="va">dat_diff</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://docs.ropensci.org/skimr/reference/skim.html">skim</a></span><span class="op">(</span><span class="va">cell_count_diff</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">dat_diff</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 7%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: left;">cell_count_diff</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-29.56</td>
<td style="text-align: right;">32.82</td>
<td style="text-align: right;">-90</td>
<td style="text-align: right;">-53</td>
<td style="text-align: right;">-17</td>
<td style="text-align: right;">-6</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">▂▃▂▂▇</td>
</tr></tbody>
</table>
</div>
</div>
<p><em>Most values are below 0, indicating the drug lowered cell counts.</em></p>
</section><section id="checking-assumptions-1" class="level2"><h2 class="anchored" data-anchor-id="checking-assumptions-1">Checking assumptions</h2>
<p>More details/descriptions can be found here:</p>
<p><a href="https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/intro-linear-models.html#specific-assumptions-for-inference-with-a-linear-model" class="uri">https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/intro-linear-models.html#specific-assumptions-for-inference-with-a-linear-model</a></p>
<p>t-test assumptions are also described in (<em>way too much</em>) detail here: <a href="https://en.wikipedia.org/wiki/Student%27s_t-test#Assumptions" class="uri">https://en.wikipedia.org/wiki/Student%27s_t-test#Assumptions</a></p>
<p><strong>The most relevant are:</strong></p>
<ul>
<li>data DIFFERENCES are independent (<em>e.g., the pairing/dependence was removed when we subtracted drug - placebo</em>), collected with a random sampling approach</li>
<li>model residuals are normally distributed</li>
<li>BUT - WE DO NOT HAVE TO WORRY ABOUT: “equal” variance assumption (<em>since there is only one column of data now that we’ve converted it to differences</em>)</li>
</ul>
<section id="in-practical-terms-just-check-to-make-sure-during-exploratory-analysis-1" class="level4"><h4 class="anchored" data-anchor-id="in-practical-terms-just-check-to-make-sure-during-exploratory-analysis-1">In practical terms just check to make sure during exploratory analysis:</h4>
<ol type="1">
<li>there are <u>no</u> large outliers in <em>the differences</em>
</li>
<li>the distribution of <em>the differences</em> is <u>not</u> highly skewed</li>
</ol>
<p><strong>If both of these are the case, then you can be confident in calculating 95% CI and using that as a basis for comparison.</strong> Note: these <u><strong>assumptions also apply to a paired and one-sample t-tests</strong></u>.</p>
<p><u><em>If there are large outliers or one the distribution is <strong>very highly</strong> skewed</em></u><em>, then you could consider options for calculating the 95% CIs (e.g., bootstrapping), or using a General<strong>ized</strong> Linear Model or running a non-parametric test procedure.</em></p>
</section></section><section id="descriptive-statistics-of-the-difference-values" class="level2"><h2 class="anchored" data-anchor-id="descriptive-statistics-of-the-difference-values">Descriptive statistics of the difference values</h2>
<p><em>Remember - if the average difference in near 0 then the drug had no/minimal effect</em></p>
<p><strong>For the numerical response variable cell_count_diff we’ll calculate:</strong></p>
<ul>
<li>
<strong>mean</strong>: <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code>
</li>
<li>
<strong>standard deviation</strong> (<strong><em>spread in data</em></strong>): <code><a href="https://rdrr.io/r/stats/sd.html">sd()</a></code>
</li>
<li>
<strong>sample size</strong>: <code><a href="https://dplyr.tidyverse.org/reference/context.html">n()</a></code>
</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat_diff</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>mean_count_diff <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">cell_count_diff</span><span class="op">)</span>,</span>
<span>            sd_count_diff <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">cell_count_diff</span><span class="op">)</span>,</span>
<span>            n_count_diff <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  mean_count_diff sd_count_diff n_count_diff
            &lt;dbl&gt;         &lt;dbl&gt;        &lt;int&gt;
1           -29.6          32.8            9</code></pre>
</div>
</div>
</section><section id="fit-linear-model-1" class="level2"><h2 class="anchored" data-anchor-id="fit-linear-model-1">Fit linear model</h2>
<ul>
<li>
<p>in <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> formula:</p>
<ul>
<li><p>Y ~ X</p></li>
<li><p>Response (<em>numeric variable</em>) ~ Explanatory (<em>in this case we just put ~1 because there is no categorical explanatory variable after we converted the data to differences</em>)</p></li>
</ul>
</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">lm_cell_diff</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">cell_count_diff</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">dat_diff</span><span class="op">)</span></span>
<span><span class="va">lm_cell_diff</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = cell_count_diff ~ 1, data = dat_diff)

Coefficients:
(Intercept)  
     -29.56  </code></pre>
</div>
</div>
<section id="coefficient-table-1" class="level3"><h3 class="anchored" data-anchor-id="coefficient-table-1">Coefficient table</h3>
<p>Create a “coefficient table” in a “tidy” table format using <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> function from broom package, with a <code>conf.int = T</code> argument to include calculation of 95% CIs.</p>
<ul>
<li>
<em>Note: often the coefficient table for a linear model is not the most useful/friendly format and can include some irrelevant information. However, in this simplified case of a single mean of the differences (estimate column)</em> the 95% CIs produced are the same as those in the emmeans table below.</li>
<li>The p-value here can also be reported in your results - it is for the significance test: <em>Is the mean of the differences significantly different from 0?</em>
<ul>
<li>Or a better interpretation of the p-value here is: <em>what is the probability of getting this data if there was no difference between the paired cell counts?</em>
</li>
<li>And interpret it as a %: <em>There is only a 2.7% chance that these data came from a true population where there was no difference between paired cell counts.</em>
</li>
</ul>
</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># use tidy function from broom package with the linear model object</span></span>
<span><span class="va">lm_len_supp_coef</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">lm_cell_diff</span>, conf.int <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lm_len_supp_coef</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  term        estimate std.error statistic p.value conf.low conf.high
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)    -29.6      10.9     -2.70  0.0270    -54.8     -4.33</code></pre>
</div>
</div>
</section></section><section id="create-emmeans-table-1" class="level2"><h2 class="anchored" data-anchor-id="create-emmeans-table-1">Create emmeans table</h2>
<p>Using <code><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans()</a></code> function from the <strong>emmeans package</strong></p>
<ul>
<li><p>Provides the basics: <a href="https://cran.r-project.org/web/packages/emmeans/vignettes/AQuickStart.html" class="uri">https://cran.r-project.org/web/packages/emmeans/vignettes/AQuickStart.html</a></p></li>
<li><p>&amp; Lots of vignettes for other uses of functions in this package: <a href="https://cran.r-project.org/web/packages/emmeans/index.html" class="uri">https://cran.r-project.org/web/packages/emmeans/index.html</a></p></li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># create emmeans table object</span></span>
<span><span class="va">lm_cell_diff_emm</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans</a></span><span class="op">(</span><span class="va">lm_cell_diff</span>, <span class="op">~</span> <span class="fl">1</span><span class="op">)</span></span>
<span></span>
<span><span class="va">lm_cell_diff_emm</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> 1       emmean   SE df lower.CL upper.CL
 overall  -29.6 10.9  8    -54.8    -4.33

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p><em>The drug lowered cell counts by an average of 29.6 cells relative to the placebo.</em> <em>95% CIs are from -54.8 to -4.3 (i.e., if we repeated the experiment, 95% of the time the true mean would be in this interval).</em> <em>At the same time this 95% CI is pretty wide, which is to be expected with only 9 individuals in the study and a decent about of “patient-to-patient” variability in cell count differences (including a couple cases that had 0 or positive count differences).</em></p>
<ul>
<li>
<strong>The mean (emmean column) in the emmeans table</strong> is technically a “modeled” mean, but here, and for many linear models, these will be equal to the sampled mean (the mean of the differences calculated we calcualted from the data above). This may not be the case for some more complicated models.</li>
<li>
<strong>The 95% CIs in the emmeans table</strong> (lower.CL to upper.CL) are calculated using all the data in the model (using a pooled standard deviation and sample size across both groups of data). However, in this case there is only one group of data so the 95% CIs here are the same as the one in the coefficient table above.</li>
</ul>
<p><em>NOTE: we will NOT make a “Contrasts Table” here because there is only one mean (and we are comparing that to 0). In the tooth cell length analysis above we had 2 means to compare and the contrasts table reports the difference between those 2 means and the 95% CI of that difference.</em></p>
</section><section id="points-mean-plot-w-model-95-cis" class="level2"><h2 class="anchored" data-anchor-id="points-mean-plot-w-model-95-cis">Points &amp; Mean plot w/ (model) 95% CIs</h2>
<div class="cell">
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># NOTE in ggplot code below we had to turn the emmeans object into </span></span>
<span><span class="co"># a tibble (data.frame) so it would work as data in ggplot</span></span>
<span><span class="va">plot_lm_cell_diff_emm</span> <span class="op">&lt;-</span> <span class="va">dat_diff</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">cell_count_diff</span>, y <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co">#use emm object as 2nd data table to plot 95% CIs</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_crossbar</a></span><span class="op">(</span>data <span class="op">=</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="va">lm_cell_diff_emm</span><span class="op">)</span>,</span>
<span>                <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">emmean</span>,</span>
<span>                    xmin <span class="op">=</span> <span class="va">lower.CL</span>,</span>
<span>                    xmax <span class="op">=</span> <span class="va">upper.CL</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Difference in cell counts with drug"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"top"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co">#remove y-axis elements</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span></span>
<span>    axis.title.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>    axis.text.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>    axis.ticks.y <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span><span class="op">(</span><span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fl">0</span>,</span>
<span>             color <span class="op">=</span> <span class="st">"red"</span>,</span>
<span>             linewidth <span class="op">=</span> <span class="fl">1.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3</span>, alpha <span class="op">=</span> <span class="fl">0.4</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The alpha argument in geom_point makes the points transparent so </span></span>
<span><span class="co"># if they overlapped you should be able to see both overlapping points.</span></span>
<span></span>
<span><span class="va">plot_lm_cell_diff_emm</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Compare_means_independent_paried_samples_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="384"></p>
</div>
</div>
<p><em>The mean (drug - placebo</em>) <em>difference was -29.6 (thicker vertical line). And the 95% CIs are from -54.8 to -4.3 (i.e., if we repeated the experiment, 95% of the time the true mean would be in this interval). At the same time this 95% CI is pretty wide, which is to be expected with only 9 individuals in the study and a decent about of patient to patient variability in cell count differences (including a couple cases that had 0 or positive count differences).</em></p>
<ul>
<li>The thick red line at 0 is there for reference since if both the placebo and drug treatments had the same (or no) effect on patent cell counts, the difference between them would be 0.</li>
</ul>
<p>Note: <code><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_pointrange()</a></code> could be used instead of <code><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_crossbar()</a></code> if you prefer that style of plotting a mean with 95% CIs <a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html" class="uri">https://ggplot2.tidyverse.org/reference/geom_linerange.html</a> (scroll down to bottom of page to see various examples of ways to plot error bars around a mean)</p>
</section><section id="combine-plots-into-a-single-results-figure-1" class="level2"><h2 class="anchored" data-anchor-id="combine-plots-into-a-single-results-figure-1">Combine plots into a single results figure</h2>
<p>We’ll use the <code><a href="https://wilkelab.org/cowplot/reference/plot_grid.html">plot_grid()</a></code> function from the <strong>cowplot package</strong> to combine our two plots above into a single results figure</p>
<ul>
<li>The <code>align = "v"</code> and <code>axis = "rl"</code> arguments make the axes of our 2 plots line up appropriately when combined. See help file for more detail: <a href="https://rdrr.io/cran/cowplot/man/plot_grid.html" class="uri">https://rdrr.io/cran/cowplot/man/plot_grid.html</a>
</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># We will combine the plot of the differences w/ 95% CI with</span></span>
<span><span class="co"># the initial plot we made the connects each placebo &amp; drug point with a line</span></span>
<span><span class="va">results_plot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://wilkelab.org/cowplot/reference/plot_grid.html">plot_grid</a></span><span class="op">(</span></span>
<span>  <span class="va">plot_lm_cell_diff_emm</span>,</span>
<span>  <span class="va">plot_dat_paired</span>,</span>
<span>  nrow <span class="op">=</span> <span class="fl">2</span>,</span>
<span>  align <span class="op">=</span> <span class="st">"v"</span>,</span>
<span>  axis <span class="op">=</span> <span class="st">"rl"</span>,</span>
<span>  rel_heights <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.25</span>, <span class="fl">1</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="co"># rel_heights argument specifies relative size of two </span></span>
<span><span class="co"># plots (i.e., first plot is 0.25 as tall as the second plot)</span></span>
<span></span>
<span><span class="va">results_plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Compare_means_independent_paried_samples_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="384"></p>
</div>
</div>
</section><section id="export-save-plot-to-a-.png-file-with-ggsave-1" class="level2"><h2 class="anchored" data-anchor-id="export-save-plot-to-a-.png-file-with-ggsave-1">Export (save) plot to a .png file with ggsave()</h2>
<ul>
<li><p>the file will be saved to your “working directory” (typically <u>the folder where your .qmd file is</u>). <strong>You’ll need to look in that folder to see the .png file!</strong></p></li>
<li><p><strong>You identify the type of file format you want to save it to with the <u>file name extension</u> at the end of the file name</strong>. Here we use <strong>.png</strong> (a great default for putting images into word docs or PPT presentations). But many others are available such as: “.pdf” (easy to view or email a .pdf to someone; and good to use for uploading plot files to journals if they’ll accept this format), “.eps” (another vector format some journals one), “.png”, “.jpeg”, “.tiff”, “.svg”(use for further editing in <a href="https://inkscape.org/" class="uri">https://inkscape.org/</a> freeware on windows).</p></li>
<li><p>You can read more about the difference between <strong><em>vector vs.&nbsp;raster</em></strong> image file types here: <a href="https://guides.lib.umich.edu/c.php?g=282942&amp;p=1885352" class="uri">https://guides.lib.umich.edu/c.php?g=282942&amp;p=1885352</a>. And more about specific file types here: <a href="https://guides.lib.umich.edu/c.php?g=282942&amp;p=1885348" class="uri">https://guides.lib.umich.edu/c.php?g=282942&amp;p=1885348</a></p></li>
<li><p>You specify the dimensions of the plot with the <code>width =</code> and <code>height =</code> arguments, default is inches. Try different widths and heights (<em>keeping in mind what would fit on a 8in by 11in page size</em>) and see what works for the plot you making. Often a plot shows the data better when it is taller or wider (<strong><em>so try different ratios of width to height</em></strong>).</p></li>
<li><p>You can also specify the image “quality” using the “dots per inch” argument <code>dpi =</code> and typically you want to use 300 or 600 for a high quality image. Depending on the file type (with .tiff for example) 600 dpi can sometimes create huge file sizes, but that is usually where I start (<em>then only go down to 300 if needed</em>).</p></li>
<li><p><em>NOTE - sometimes you can get an error when running <code><a href="https://ggplot2.tidyverse.org/reference/ggsave.html">ggsave()</a></code> repeatedly if the saved .png file is already open on your computer in your image viewer - need to close it each time you want to edit and re-output the image file.</em></p></li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># output plot to .png file type, set size (default is inches), 300 or 600 dpi is high quality</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsave.html">ggsave</a></span><span class="op">(</span></span>
<span>  <span class="st">"plot_cell_diff_95CIs.png"</span>,</span>
<span>  <span class="va">results_plot</span>,</span>
<span>  width <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  height <span class="op">=</span> <span class="fl">4</span>,</span>
<span>  dpi <span class="op">=</span> <span class="fl">600</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="results-sentence-1" class="level2"><h2 class="anchored" data-anchor-id="results-sentence-1">Results sentence</h2>
<ul>
<li>You should include both the <strong>magnitude (effect size)</strong> and <strong>direction</strong> of difference</li>
<li>Focus on the biology and <em>do not make a statistical result the subject of the sentence</em>.</li>
</ul>
<p><strong>The drug decreased cell counts by an average of 29.6 cells (95% CI: 4.3 to 54.8, p = 0.027) compared to taking a placebo (Fig. X).</strong></p>
<ul>
<li>Figure X would be combined results plot above with effects plot on top (w/ 95% CI of mean differences) and plot witht he original data points on the bottom.</li>
<li>the p-value could be found in the contrasts table above or in the t-test outputs below.</li>
</ul>
<p>More explanation of why it is optional to (and why this author advises you don’t need to) use the word “significant” in the results can be found here (<em>but if you or your adviser want to, that is fine too, since p-value is &lt; 0.05</em>) and other examples of writing results can be found here: <a href="https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/oneway.html#step-7-report-the-model-results" class="uri">https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/oneway.html#step-7-report-the-model-results</a></p>
</section><section id="paired-sample-t-test-or-one-sample-t-test-w-mu-0" class="level2"><h2 class="anchored" data-anchor-id="paired-sample-t-test-or-one-sample-t-test-w-mu-0">Paired-Sample t-test (or one-sample t-test w/ mu = 0)</h2>
<p><strong>Statistical Hypotheses (for a Paired-Sample t-test)</strong></p>
<p><em>Null Hypothesis:</em> mean of the differences in the population is equal to 0</p>
<p><em>Alternative Hypothesis:</em> mean of the differences in the population is NOT equal to 0</p>
<hr>
<p>There are two ways to specify a paired-t-test using the <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> function both yield the same results.</p>
<p>(my preferred method) Calculate the differences, then run a one-sample t-test with the constant = 0 (<em>that you are comparing the mean of the differences to</em>):</p>
<ul>
<li>
<strong>differences_variable ~ 1</strong> (<em>use 1 since there is no explanatory variable</em>)</li>
<li>then set the <em>a prior</em> constant to 0 with argument <code>mu = 0</code>
</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># using differences data table, run as one-sample t-test compared to 0</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">cell_count_diff</span> <span class="op">~</span> <span class="fl">1</span>, mu<span class="op">=</span><span class="fl">0</span>, data <span class="op">=</span> <span class="va">dat_diff</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  cell_count_diff
t = -2.7014, df = 8, p-value = 0.02701
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 -54.784709  -4.326402
sample estimates:
mean of x 
-29.55556 </code></pre>
</div>
</div>
<p>Or w/ Paired Data:</p>
<ul>
<li><strong>specify with formula: response ~ explanatory</strong></li>
<li>then add argument <code>paired = TRUE</code> (which then has the t.test function calculate the differences for you)</li>
<li>
<strong><em>NOTE - DATA MUST BE SORTED so each pair is in the same order by explanatory variable, here data was entered that way, but you could use the dplyr function <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> to sort rows if necessary</em></strong> <a href="https://dplyr.tidyverse.org/reference/arrange.html" class="uri">https://dplyr.tidyverse.org/reference/arrange.html</a>
</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># using paired data table, run as actual paired-sample t-test</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">cell_count</span><span class="op">~</span><span class="va">treatment</span>, data <span class="op">=</span> <span class="va">dat_paired</span>, paired <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  cell_count by treatment
t = 2.7014, df = 8, p-value = 0.02701
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
  4.326402 54.784709
sample estimates:
mean difference 
       29.55556 </code></pre>
</div>
</div>
<p><em>Both methods yield identical results, with the exception of sign differences (negative/positive) on the mean difference and t-statistic values (which just depends on the order of the pairs in the data set when the differences are calculated), so just keep track of what is being subtracted from what.</em></p>
<hr>
<section id="extra-use-of-broom-package-tidy-function-w-t.test-1" class="level3"><h3 class="anchored" data-anchor-id="extra-use-of-broom-package-tidy-function-w-t.test-1">Extra: Use of broom package tidy() function w/ t.test()</h3>
<ul>
<li><p>Can also wrap the <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> function from broom package around the t.test, to get a “tidy” output with the same values organized in a data.frame</p></li>
<li><p>Can be useful if you want to store the results and directly output values (like p-value or CIs etc.)</p></li>
</ul>
<p><a href="https://cran.r-project.org/web/packages/broom/vignettes/broom.html" class="uri">https://cran.r-project.org/web/packages/broom/vignettes/broom.html</a></p>
<div class="cell">
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">t_test_cell_diff</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">cell_count_diff</span> <span class="op">~</span> <span class="fl">1</span>, mu<span class="op">=</span><span class="fl">0</span>, data <span class="op">=</span> <span class="va">dat_diff</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># show results in "tidy" data.frame format (from broom package)</span></span>
<span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">t_test_cell_diff</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 8
  estimate statistic p.value parameter conf.low conf.high method     alternative
     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;      
1    -29.6     -2.70  0.0270         8    -54.8     -4.33 One Sampl… two.sided  </code></pre>
</div>
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># select mean difference, 95%CIs and p-value</span></span>
<span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">t_test_cell_diff</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">estimate</span>, <span class="va">conf.low</span>, <span class="va">conf.high</span>, <span class="va">p.value</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  estimate conf.low conf.high p.value
     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1    -29.6    -54.8     -4.33  0.0270</code></pre>
</div>
</div>
<hr>


</section></section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">This is a quarto built website <a href="https://quarto.org/docs/websites" class="uri">https://quarto.org/docs/websites</a>.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
<li class="nav-item compact">
    <a class="nav-link" href="https://claisselab.com">
      <i class="bi bi-house-fill" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ClaisseLab">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
</div>
  </div>
</footer>


</body></html>